upstream backend {
    server unix:/var/run/php5-fpm.sock1 weight=100 max_fails=5 fail_timeout=5;
    server unix:/var/run/php5-fpm.sock2 weight=100 max_fails=5 fail_timeout=5;
}
server {
    listen 80;
    server_name yeyun.welkin.com hssfxy.welkin.com hocml.welkin.com;
    root /home/wwwroot/yeyun/public;
    #error_log /var/log/nginx/edusoho.error.log;
    #access_log off;
    access_log /var/log/nginx/access.log main buffer=16k;
    log_not_found off;
    error_log /var/log/nginx-error.log warn;
    location / {
        index index.php;
        try_files $uri @rewriteapp;
    }
    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }
    location ~ ^/csecy {
        internal;
        root /home/wwwroot/csecy/public;
    }

    location ~ \.php(/|$) {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS              off;
        fastcgi_param HTTP_X-Sendfile-Type X-Accel-Redirect;
        fastcgi_param HTTP_X-Accel-Mapping /udisk=/home/welkin/yeyun/udisk;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 8 128k;
    }
    location ~* \.(jpg|jpeg|gif|png|ico|swf)$ {
        expires 3y;
        access_log off;
        gzip off;
    }
    location ~* \.(css|js)$ {
        access_log off;
        expires 3y;
    }
    location ~ ^/files/.*\.(php|php5)$ {
        deny all;
    }
}
